### PR TITLE
Basic win32 support

### PR DESCRIPTION
**Pull request by wh0am1-dev**
__Not tested on macOS !__ Make sure that it still works before merging.

## Regarding #2

- `app.dock` is not the only macOS only method used throughout the project, `Tray.setTitle` is macOS only as well.
- Neither [Tray](https://github.com/electron/electron/blob/master/docs/api/tray.md) nor [maxogden/menubar](https://github.com/maxogden/menubar) support displaying text on Windows taskbar notification area.

So, I've placed the title in a tooltip, shown when hovering with the mouse over the icon. Only on Windows, to avoid changing the previous behavior on macOS.

I've also found that on Windows, right clicking over the icon defaults to opening the menu, but this button was supposed to toggle decimal format. I've changed the format toggle button to left click on Windows.

### CODE REVIEW

**Comment by neauoire** [comment]
Mhmm you've changed my build scripts paths XD
I'll test it for OSX today :)

**Comment by wh0am1-dev** [comment]
There's no.  `~/Desktop` on Windows, using a local folder allows cross-platform building. And `builds/` was already in your `.gitignore`.

**Comment by neauoire** [comment]
Right. Fair point.

**Comment by kormyen** [comment]
I was trying to think of or find a way to display the 'beat' value as text on the Windows taskbar. The best (read: horrible) way I've thought of so far is to have three separate apps, one for each digit. 

It is at least possible somehow to display update-able numbers in a tray icon as cpu-temperature monitoring services do it like: https://www.howtogeek.com/wp-content/uploads/2016/09/screenshot.1-2.png

Maybe its possible to cram three digits into one icon but it would be quite small.

I wish there was a way to replace the system clock. Customization options of it seem very limited.

**Pull request merged**
