### PR TITLE
Reminder notifications

### PR DESCRIPTION
**Pull request by wh0am1-dev**
## Background

Last weekend I was diagnosed with scoliosis. Keep calm, it's on an early state, fixable, but I need to keep in mind getting off this chair every now and then, stretch the muscles and blah, blah, blah... As of right now I'm sitting here 1000/7.

So I thought: "how about notifications !? :)".

## Changes

- First of all, I've fixed some residual semicolons I left on `package.json` from my previous pull request... I'm sorry for that. It was greedy from me changing the build scripts like that, it's not my project. I've avoided changing the version number this time too, so it's up to you, @neauoire !
- I've added a new dependency: [node-notifier](https://www.npmjs.com/package/node-notifier). Electron comes with its own `Notification` API, but I've tested it and it doesn't work properly across platforms. `node-notifier` seems to work as intended and it comes with an easy to use API.
- There's a new option in the menu to mute notifications, just in case.
- I've also sorted the menu so it now displays different sections:
    - Calendar
    - Pomodoro
    - Settings
    - Quit

### CODE REVIEW

**Comment by wh0am1-dev** [comment]
btw, I've only tested on Windows !

**Comment by wh0am1-dev** [comment]
Take a look at this if it doesn't work when compiled: [node-notifier within electron packaging](https://www.npmjs.com/package/node-notifier#within-electron-packaging)

**Comment by neauoire** [comment]
screen shot 2018-05-25 at 8 33 22 am

Works well on OSX 👍 
Sorry to hear about you being sick and all, I hope that maybe the clock can serve you as a reminder to stand up and go for a walk every now and then!

**Comment by wh0am1-dev** [comment]
Thank you, it'll help, for sure :)

**Pull request merged**
